#!/bin/bash
movies=("Thanman" "AR" "auto" "seenu" "Ramu")

for i in ${movies[@]}
do
        echo $i

        if[ $i -eq "ABC" ]

        then
            exit 1
        else
            echo "not found"
        fi
done

